# Generated by Django 2.1.3 on 2018-11-08 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musicList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('urls', models.TextField()),
                ('title', models.CharField(default='music', max_length=50)),
                ('start_point', models.IntegerField()),
                ('end_point', models.IntegerField()),
            ],
        ),
    ]
