# Generated by Django 2.1.3 on 2018-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0003_auto_20181123_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicstorage',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
