# Generated by Django 2.1.3 on 2018-11-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0004_auto_20181124_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedMusicList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='music', max_length=50)),
                ('musician', models.CharField(default='music singer', max_length=50)),
                ('highlightFile', models.FileField(upload_to='output/')),
            ],
        ),
        migrations.DeleteModel(
            name='musicList',
        ),
        migrations.AlterField(
            model_name='musicstorage',
            name='file',
            field=models.FileField(upload_to='music/'),
        ),
    ]
